let viz = d3.select("#container")
  .append("svg")
  .attr("id", "viz")
  .attr("width", 1200)
  .attr("height", 1800)
;
var svg = d3.select('svg');

var text = svg.append('text')
                              .text('About')
                              .attr("x",120)
                              .attr('y',72)
                              .attr("fill", "black")
                              .style("font-size", "32px")

var text = svg.append('text')
                              .text('What is Steam？')
                              .attr("x",320)
                              .attr('y',172)
                              .attr("fill", "black")
                              .style("font-size", "24px")

var myimage = svg.append('image')
                              .attr('xlink:href', 'steam.jpg')
                              .attr("x",100)
                              .attr('y',122)
                              .attr('width', 200)
                              .attr('height', 200)

var text = svg.append('text')
                              .text('Steam is a video game digital distribution service by Valve.')
                              .attr("x",320)
                              .attr('y',220)
                              .attr("fill", "black")
                              .style("font-size", "16px")

var text = svg.append('text')
                              .text('It was launched as a standalone software client in September 2003')
                              .attr("x",320)
                              .attr('y',240)
                              .attr("fill", "black")
                              .style("font-size", "16px")

var text = svg.append('text')
                              .text('as a way for Valve to provide automatic updates for their games')
                              .attr("x",320)
                              .attr('y',260)
                              .attr("fill", "black")
                              .style("font-size", "16px")

var text = svg.append('text')
                              .text('and expanded to include games from third-party publishers.')
                              .attr("x",320)
                              .attr('y',280)
                              .attr("fill", "black")
                              .style("font-size", "16px")
var myimage = svg.append('image')
                              .attr('xlink:href', 'library.jpg')
                              .attr("x",200)
                              .attr('y',422)
