let viz = d3.select("#container")
  .append("svg")
  .attr("id", "viz")
  .attr("width", 2000)
  .attr("height", 1600)
;
var svg = d3.select('svg');

var text = svg.append('text')
                              .text('About')
                              .attr("x",120)
                              .attr('y',72)
                              .attr("fill", "black")
                              .style("font-size", "32px")

var text = svg.append('text')
                              .text('What is Steam？')
                              .attr("x",320)
                              .attr('y',172)
                              .attr("fill", "black")
                              .style("font-size", "24px")

var myimage = svg.append('image')
                              .attr('xlink:href', 'steam.jpg')
                              .attr("x",100)
                              .attr('y',122)
                              .attr('width', 200)
                              .attr('height', 200)

var text = svg.append('text')
                              .text('Steam is a video game digital distribution service by Valve.')
                              .attr("x",320)
                              .attr('y',220)
                              .attr("fill", "black")
                              .style("font-size", "16px")

var text = svg.append('text')
                              .text('It was launched as a standalone software client in September 2003')
                              .attr("x",320)
                              .attr('y',240)
                              .attr("fill", "black")
                              .style("font-size", "16px")

var text = svg.append('text')
                              .text('as a way for Valve to provide automatic updates for their games')
                              .attr("x",320)
                              .attr('y',260)
                              .attr("fill", "black")
                              .style("font-size", "16px")

var text = svg.append('text')
                              .text('and expanded to include games from third-party publishers.')
                              .attr("x",320)
                              .attr('y',280)
                              .attr("fill", "black")
                              .style("font-size", "16px")


var text = svg.append('text')
                              .text('There is no significant correlations of the users’ interests. Some players play one game ')
                              .attr("x",320)
                              .attr('y',480)
                              .attr("fill", "black")
                              .style("font-size", "16px");
//
var text = svg.append('text')
                              .text('hundreds of hours while others play huge amount of games in different types.')
                              .attr("x",320)
                              .attr('y',510)
                              .attr("fill", "black")
                              .style("font-size", "16px")
//
var text = svg.append('text')
                              .text('The data indicates that Competitive games have more players.')
                              .attr("x",320)
                              .attr('y',570)
                              .attr("fill", "blue")
                              .style("font-size", "16px")
//
var image2 = svg.append('image')
                              .attr('xlink:href', 'dota2.jpg')
                              .attr("x",100)
                              .attr('y',422)
                              .attr('width', 200)
                              .attr('height', 200)

//
var text = svg.append('text')
                              .text('time spend on games cannot represent the game quality and player’s preference')
                              .attr("x",320)
                              .attr('y',770)
                              .attr("fill", "black")
                              .style("font-size", "16px")
//
var text = svg.append('text')
                              .text('because the gameplays are different.')
                              .attr("x",320)
                              .attr('y',810)
                              .attr("fill", "black")
                              .style("font-size", "16px")
//
var text = svg.append('text')
                              .text('The ratio of time spent on one game and the complete time spent by the player would')
                              .attr("x",320)
                              .attr('y',850)
                              .attr("fill", "black")
                              .style("font-size", "16px")
//
var text = svg.append('text')
                              .text('better illustrate one’s game preference')
                              .attr("x",320)
                              .attr('y',890)
                              .attr("fill", "black")
                              .style("font-size", "16px")
//
var image2 = svg.append('image')
                              .attr('xlink:href', 'gameplay.png')
                              .attr("x",100)
                              .attr('y',730)
                              .attr('width', 200)
                              .attr('height', 200)

//
var image2 = svg.append('image')
                              .attr('xlink:href', 'videogame.gif')
                              .attr("x",550)
                              .attr('y',1000)
                              .attr('width', 400)
                              .attr('height', 400)
