
let viz = d3.select("#container")
.append("svg")
.attr("id", "viz")
.attr("width", 1600)
.attr("height", 800)
;
var svg = d3.select('svg');

data=[1724,820,507,379,284,257,252,225,195,182]
games = new Array(2652)

viz.selectAll("circle").data(games).enter().append("circle")
                                                 .attr("r", 5)
                                                 .style("opacity", .5)
                                                 .attr("fill","LightSkyBlue")
                                                 .attr("cx", d3.randomUniform(10, 800))
                                                 .attr("cy",d3.randomUniform(10, 800))

 svg.append('circle')
   .attr('r', 5)
   .attr("cx", d3.randomUniform(10, 800))
   .attr("cy",d3.randomUniform(10, 600))
   .attr('fill', 'LightSkyBlue')
   .transition()
   .duration(2000)
   .attr('fill', '#000000')
   .attr('cx', 200)
   .attr('cy', 250)
   .attr("r",data[0]/10)

svg.append('circle')
   .attr('r', 5)
   .attr("cx", d3.randomUniform(10, 800))
   .attr("cy",d3.randomUniform(10, 600))
   .attr('fill', 'LightSkyBlue')
   .transition()
   .duration(2000)
   .attr('fill', '#443535')
   .attr('cx', 470)
   .attr('cy', 340)
   .attr("r",data[1]/10)

svg.append('circle')
   .attr('r', 5)
   .attr("cx", d3.randomUniform(10, 800))
   .attr("cy",d3.randomUniform(10, 600))
    .attr('fill', 'LightSkyBlue')
   .transition()
   .duration(2000)
   .attr('fill', '#3D445F')
   .attr('cx', 360)
   .attr('cy', 440)
   .attr("r",data[2]/10)

svg.append('circle')
   .attr('r', 5)
   .attr("cx", d3.randomUniform(10, 800))
   .attr("cy",d3.randomUniform(10, 600))
    .attr('fill', 'LightSkyBlue')
   .transition()
   .duration(2000)
   .attr('fill', '#3C503E')
   .attr('cx', 460)
   .attr('cy', 480)
   .attr("r",data[3]/10)

svg.append('circle')
   .attr('r', 5)
   .attr("cx", d3.randomUniform(10, 800))
   .attr("cy",d3.randomUniform(10, 600))
   .attr('fill', 'LightSkyBlue')
   .transition()
   .duration(2000)
   .attr('fill', '#901818')
   .attr('cx', 480)
   .attr('cy', 145)
   .attr("r",data[4]/10)

svg.append('circle')
    .attr('r', 5)
    .attr("cx", d3.randomUniform(10, 800))
    .attr("cy",d3.randomUniform(10, 600))
    .attr('fill', 'LightSkyBlue')
    .transition()
    .duration(2000)
    .attr('fill', '#D5BFAE')
    .attr('cx', 430)
    .attr('cy', 210)
    .attr("r",data[5]/10)

svg.append('circle')
    .attr('r', 5)
    .attr("cx", d3.randomUniform(10, 800))
    .attr("cy",d3.randomUniform(10, 600))
    .attr('fill', 'LightSkyBlue')
    .transition()
    .duration(2000)
    .attr('fill', '#B8B3B3')
    .attr('cx', 550)
    .attr('cy', 200)
    .attr("r",data[6]/10)

svg.append('circle')
    .attr('r', 5)
    .attr("cx", d3.randomUniform(10, 800))
    .attr("cy",d3.randomUniform(10, 600))
    .attr('fill', 'LightSkyBlue')
    .transition()
    .duration(2000)
    .attr('fill', '#5593E9')
    .attr('cx', 600)
    .attr('cy', 280)
    .attr("r",data[7]/10)

svg.append('circle')
    .attr('r', 5)
    .attr("cx", d3.randomUniform(10, 800))
    .attr("cy",d3.randomUniform(10, 600))
    .attr('fill', 'LightSkyBlue')
    .transition()
    .duration(2000)
    .attr('fill', '#D6D6D6')
    .attr('cx', 750)
    .attr('cy', 280)
    .attr("r",data[8]/10)

svg.append('circle')
    .attr('r', 5)
    .attr("cx", d3.randomUniform(10, 800))
    .attr("cy",d3.randomUniform(10, 600))
    .attr('fill', 'LightSkyBlue')
    .transition()
    .duration(2000)
    .attr('fill', '#D4B757')
    .attr('cx', 675)
    .attr('cy', 205)
    .attr("r",data[9]/10)

//text
var text = svg.append('text')
    .text('Top-selling video games')
      .attr("x",920)
      .attr('y',102)
      .attr("fill", "darkblue")
      .style("font-size", "32px")


var text = svg.append('text')
    .text('Dota 2')
      .attr("x",920)
      .attr('y',172)
      .attr("fill", "black")
      .style("font-size", "22px");
var text = svg.append('text')
    .text('Team Fortress 2')
      .attr("x",920)
      .attr('y',212)
      .attr("fill", "#443535")
      .style("font-size", "22px");
var text = svg.append('text')
    .text('Counter-Strike Global Offensive')
      .attr("x",920)
      .attr('y',252)
      .attr("fill", "#3D445F")
      .style("font-size", "22px")
var text = svg.append('text')
    .text('Unturned')
      .attr("x",920)
      .attr('y',292)
      .attr("fill", "#3C503E")
      .style("font-size", "22px")
var text = svg.append('text')
    .text('Left 4 Dead 2')
      .attr("x",920)
      .attr('y',332)
      .attr("fill", "#901818")
      .style("font-size", "22px")
var text = svg.append('text')
    .text('Counter-Strike Source')
      .attr("x",920)
      .attr('y',372)
      .attr("fill", "#D5BFAE")
      .style("font-size", "22px")
var text = svg.append('text')
    .text('The Elder Scrolls V Skyrim')
      .attr("x",920)
      .attr('y',412)
      .attr("fill", "#B8B3B3")
      .style("font-size", "22px")
var text = svg.append('text')
    .text('Garry’s Mod')
      .attr("x",920)
      .attr('y',452)
      .attr("fill", "#5593E9")
      .style("font-size", "22px")
var text = svg.append('text')
    .text('Counter-Strike')
      .attr("x",920)
      .attr('y',492)
      .attr("fill", "#D6D6D6")
      .style("font-size", "22px")
var text = svg.append('text')
    .text('Sid Meier’s Civilization V')
      .attr("x",920)
      .attr('y',532)
      .attr("fill", "#D4B757")
      .style("font-size", "22px")
var text = svg.append('text')
      .text('2662 games in total')
      .attr("x",920)
      .attr('y',632)
      .attr("fill", "black")
      .style("font-size", "12px")
