let viz = d3.select("#container")
  .append("svg")
  .attr("id", "viz")
  .attr("width", 1200)
  .attr("height", 800)
;
var svg = d3.select('svg');

var text = svg.append('text')
                              .text('How to read the visualization')
                              .attr("x",120)
                              .attr('y',72)
                              .attr("fill", "white")
                              .style("font-size", "32px")
var circle = svg.append('circle')
                              .attr("cx",140)
                              .attr('cy',172)
                              .attr("r", 40)
                              .attr("fill", "white")
                              .style("opacity", .44)
                              .attr("stroke","black")
                              .attr("stroke-width",4)
                              .style("font-size", "32px")
var text = svg.append('text')
                              .text('Each circle represent one bird I saw in the neightborhood')
                              .attr("x",200)
                              .attr('y',160)
                              .attr("fill", "white")
                              .style("font-size", "22px")
var text = svg.append('text')
                              .text('The inside color of the circle is the bird color and the stroke color is the color of the tile.')
                              .attr("x",200)
                              .attr('y',200)
                              .attr("fill", "white")
                              .style("font-size", "22px")
var text = svg.append('text')
                              .text('The postion of circle in the first page is the rough direction the bird came from.')
                              .attr("x",200)
                              .attr('y',290)
                              .attr("fill", "white")
                              .style("font-size", "22px")
// direction line
var line = svg.append("line")
                              .attr("x1",140)
                              .attr("y1",260)
                              .attr("x2",140)
                              .attr("y2",300)
                              .attr("stroke","black")
                              .attr("stroke-width",2);
// axis
var line = svg.append("line")
                              .attr("x1",120)
                              .attr("y1",340)
                              .attr("x2",120)
                              .attr("y2",380)
                              .attr("stroke","black")
                              .attr("stroke-width",2)
var line = svg.append("line")
                              .attr("x1",120)
                              .attr("y1",380)
                              .attr("x2",160)
                              .attr("y2",380)
                              .attr("stroke","black")
                              .attr("stroke-width",2)


var text = svg.append('text')
                              .text('The axis indicate the height counted by floors when the bird fly and how long it stopped.')
                              .attr("x",200)
                              .attr('y',380)
                              .attr("fill", "white")
                              .style("font-size", "22px")
var myimage = svg.append('image')
                              .attr('xlink:href', 'birdSize/2.png')
                              .attr("x",140)
                              .attr('y',480)
                              .attr('width', 200)
                              .attr('height', 200)
var myimage = svg.append('image')
                              .attr('xlink:href', 'birdSize/2.png')
                              .attr("x",390)
                              .attr('y',480)
                              .attr('width', 200)
                              .attr('height', 200)
var myimage = svg.append('image')
                              .attr('xlink:href', 'birdSize/2.png')
                              .attr("x",640)
                              .attr('y',480)
                              .attr('width', 200)
                              .attr('height', 200)
var myimage = svg.append('image')
                              .attr('xlink:href', 'birdSize/2.png')
                              .attr("x",890)
                              .attr('y',480)
                              .attr('width', 200)
                              .attr('height', 200)

var text = svg.append('text')
                              .text('Documented and Created by Layla Lei(Layla).')
                              .attr("x",750)
                              .attr('y',780)
                              .attr("fill", "white")
                              .style("font-size", "18px")
